name: Build & Publish to Docker Hub

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Build latest image
        run: docker build -t sean1832/wolite:latest .

      - name: login to docker hub
        run: docker login -u sean1832 -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: push image to docker hub
        run:  docker push sean1832/wolite:latest
